modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.rainbowtulip]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rainbowtulip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
    modId="rainbowtulip"
    version="1.0.0"
    displayName="Rainbow Tulip"
    displayTags=["plants-amore"]
    description='''
        Adds a decorative Rainbow Tulip plant entity to your world.
        Spawn with: /summon rainbowtulip:rainbow_tulip ~ ~ ~
    '''
